spring:

  config:
    import: optional:file:.env.properties

  application:
    name: leetcode

  datasource:
    url: jdbc:mysql://localhost:3306/leetcode?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email,read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: 8081
  servlet:
    session:
      timeout: PT30M

frontend:
  origin: ${FRONTEND_ORIGIN}

logging:
  level:
    root: INFO
    "[com.example.leetcode]": DEBUG
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 10MB
